# Generated by Django 4.1.6 on 2023-02-16 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('gender', models.CharField(choices=[('woman', 'Женщина'), ('man', 'Мужчина'), ('other', 'Другое')], max_length=10)),
                ('diagnosis_category', models.CharField(choices=[('mouth_throat', 'Губы, полость рта и глотка'), ('stomach', 'Желудок'), ('rectum', 'Прямая кишка'), ('lungs', 'Бронхи, легкие'), ('lymph_node', 'Лимфатические узлы и кроветворная ткань'), ('other', 'Другое')], max_length=180)),
                ('diagnosis_description', models.TextField()),
                ('date_detection', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
